geoschem/integrated_methane_inversion

run_ch4_inversion.sh, setup_ch4_inversion.sh
@djvaron I think these are the only places where lat/lon arithmetic is performed within shell scripts (let me know if there are others). I tested by running the setup script and using `bc` seems to work.
=> Update setup and runscript to use bc for floating point lat/lon arithmetic

config.yml, envs/Harvard-Cannon/config.harvard-cannon.yml, run_imi.sh, setup_imi.sh
In this PR, we update the IMI scripts for GEOS-Chem 13.4.1.
1. Now create template directory using GEOS-Chem's createRunDir.sh script. By default, a GEOS-FP 0.25x0.3125 nested North America run directory will be created. Settings in input.geos for the grid and meteorology will be further modified according to the settings in config.yml. Using createRunDir.sh allows us to remove several string replacement commands for GEOS-Chem input files from setup_imi.sh.
2. Print GEOS-Chem compilation output to a log file and remove upon a successful build. This reduces text printed to the screen during setup. Build information is still archived in GEOSChem_build_info.
3. Added several cosmetic updates to output printed to the screen when executing setup_imi.sh and run_imi.sh.
4. Simplified file path …
=> Update IMI to use GEOS-Chem 13.4.1

config.yml, docs/source/advanced/custom-region.rst, docs/source/getting-started/imi-config-file.rst, envs/Harvard-Cannon/config.harvard-cannon.yml, run_imi.sh, setup_imi.sh, src/geoschem_run_scripts/ch4_run.template, src/inversion_scripts/imi_preview.py, src/utilities/crop_met.sh
This PR includes the following updates:
- Modify `setup_imi.sh` for GEOS-Chem 14.0.0. This includes replacing references to input.geos with geoschem_config.yml and changing restart file paths.
- Update configuration file and documentation to reflect new supported regional domains.
- Add minor fix to `run_imi.sh` to avoid creating a symbolic link to the TROPOMI data if it already exists.
- Increase memory requested in run script so that a simulation for the example region won't crash.
=> Update the IMI to use GEOS-Chem 14.0.0

envs/Harvard-Cannon/config.harvard-cannon.yml
Adding a missing component of config.yml to the Cannon version of the file.
=> add clustering options to Cannon config file

src/inversion_scripts/jacobian.py
`jacobian.py` should apply both the super-observation TROPOMI operator and the single-observation TROPOMI operator, and save out both results (former for use in the inversion, latter for use in visualization). Currently the viz data isn't being saved. This PR addresses that bug.
=> bug fix to make jacobian.py save viz output data

.readthedocs.yaml
Recently, a software update on the ReadTheDocs side resulted in a side-effect that caused ReadTheDocs builds to fail.   See https://github.com/readthedocs/readthedocs.org/issues/10290 for details.
As a recommendation against this from happening again, ReadTheDocs.org recommends adding a `.readthedocs.yaml` file to the root directory.  This configuration file specifies the paths to the `requirements.txt` and `conf.py` that are used by ReadTheDocs to build the documentation.  It also specifies the versions of python and other tools that are used internally.
Here we add a `.readthedocs.yaml` that is consistent with other repositories in the geoschem organization.
=> Add .readthedocs.yaml file to configure ReadTheDocs builds

run_imi.sh, src/utilities/test_TROPOMI_dir.py
We had an issue in the past where `download_TROPOMI.py` would result in users having duplicate TROPOMI files (e.g., two files with orbit number xxxxx, but one with processor version 02.04.00 and one with processor version 01.03.00). This simple  and fast test should prevent this in the future as processor version numbers continue to change.
=> Make sure there are not duplicate TROPOMI files

src/inversion_scripts/operators/TROPOMI_operator.py
Name: Sabour Baray
Institution: Environment and Climate Change Canada
In the recently updated RPRO dataset, there appear to be some edge cases where an orbit file can be opened correctly, but still return a hdf5 error when trying to read a variable later on. This can interrupt the process of reading all TROPOMI files for a given time period.
I've shared another [script](https://github.com/sabourbaray/download_copernicus_py) that validates our local TROPOMI cache with the Copernicus repository by comparing exact filesizes, so I've double checked the files in our download process. It may be the case that these are files that could be problematic for any user.
Moving the error-catch to include all variables fixes this problem for me.
=> bugfix to catch errors in TROPOMI variables

src/components/jacobian_component/jacobian.sh, src/components/posterior_component/posterior.sh, src/components/setup_component/setup.sh, src/components/template_component/template.sh
Name: Sabour Baray
Institution: Environment and Climate Change Canada
For the extra observation operators (GOSAT, TCCON, AIRS, Planeflight), currently the IMI switches them on in the template run, which is used to update the geoschem_config.yml files in all run directories. Users will likely only use these comparisons for the base run and posterior run, so we can save computational cost by not running these operators for each jacobian run.
=> bugfix to only turn on extra observation switches for prior and posterior runs

src/notebooks/visualization_notebook.ipynb
We noticed a bug in the visualization notebook DOFS calculation. This only occurs when using clustering. In `make_gridded_posterior.py` we map the calculated sensitivity values to the corresponding state vector elements. Eg. if element 3 has a sensitivity of .5, and is composed of 10 grid cells, then all 10 grid cells are set to .5. However, in `visualization_notebook.ipynb` the way we calculate DOFS is `np.nansum(avkern_ROI.values)` which sums every .25 degree grid cell. Per the example, we are effectively overcounting the sensitivity of element 3 by 10x. 
To fix this we simply use the un-gridded inversion result from `inversion_result.nc` to calculate DOFS.
Credit to Alex Oort Alonso for flagging this bug!
Confirmed that this fix works in …
=> Bugfix: Fix DOFS calculation

src/notebooks/statevector_from_shapefile.ipynb, src/utilities/make_state_vector_file.py
This PR addresses the following bugs in make_state_vector.py:
- an offset was mistakenly being applied in non 0.25 degree resolution grids
- faulty if statement caused land threshold to always evaluated to false
- In some cases labels would not be applied to buffer cells, causing gaps in the statevector labels resulting in perturbation simulations that would not be perturbed at all. This seems to only occur when using custom state vectors from a shapefile
To fix the 3rd bug I updated the buffer cell creation code and aligned them in `src/utilities/make_state_vector_file.py` and `src/notebooks/statevector_from_shapefile.ipynb`
@eastjames, tagging you and issue #181
=> Fix bugs in make_state_vector.py

src/components/inversion_component/inversion.sh, src/utilities/cleanup_script.sh
Simple interactive utility script for cleanup of IMI output. Currently set up to delete:
- `OutputDir` files for jacobian simulations except for prior and background simulation
- `data_sensitivities` files in either normal or KF mode
I also include a dry-run mode that prints all the directories that will have recursive deletions without performing the removals.
Usage is:
`./cleanup_script.sh <config_file_path.yml>`
@djvaron @msulprizio @nicholasbalasus @eastjames please let me know if you think of additional files/directories that should be optionally deleted with this script
=> Feature: cleanup script

.github/workflows/stale.yml
The stale Github action is activated her. Issues with no activity in 60 days will be tagged as stale and if no action is taken they will be closed 7 days later. See https://github.com/actions/stale for more information on this Github action.
Note: For this action to take effect, it must be in the `main` branch. If preferred, I can change the base branch of this pull request to `dev` if we're willing to wait until the IMI 2.0 release for this action to start.
=> Add stale Github action to automatically tag and close stale issues

run_imi.sh, src/components/inversion_component/inversion.sh, src/components/jacobian_component/jacobian.sh, src/components/posterior_component/posterior.sh, src/components/setup_component/setup.sh
This is related to running the IMI at Harvard on Cannon. For @laestrada and I, the combination of first sourcing the GEOS-Chem environment file and then activating the conda environment (an alias for micromamba in our case) results in GEOS-Chem not being able to run (`./gcclassic: error while loading shared libraries: libnetcdf.so.18: cannot open shared object file: No such file or directory`).
This order was introduced in https://github.com/geoschem/integrated_methane_inversion/commit/7c57d9182660319e52f45c09c8ec5b9286ef4650. This PR is a fix that makes sure the Conda environment and GEOS-Chem environment file are only activated a single time each (now in `run_imi.sh`) and than the order is Conda then GEOS-Chem environment file. I have tested this …
=> Bug fix for environment file activations

src/components/jacobian_component/jacobian.sh, src/components/preview_component/preview.sh, src/components/statevector_component/aggregation.py, src/components/statevector_component/statevector.sh, src/geoschem_run_scripts/ch4_run.template, src/geoschem_run_scripts/run_jacobian_simulations.sh, src/geoschem_run_scripts/run_prior_simulation.sh, src/geoschem_run_scripts/submit_jacobian_simulations_array.sh, src/inversion_scripts/imi_preview.py
It can be shown with a simple bash script like the one below that if you run a job using sbatch with output to `out.log` and then start another job within using sbatch again and try to append to the same `out.log` that the output of the inner job will be overwritten by the outer job. I find that this is only true if the two jobs take place on different nodes. I'm not sure if this is a SLURM bug or intended behavior.
```
#!/bin/bash
#SBATCH -p test
#SBATCH -o "out.log"
echo "1"
sbatch -W -p sapphire --wrap "echo '2' >> out.log"
echo "3"
```
In the IMI, this is responsible for the behavior seen in #136 and #187. This PR fixes this by writing to a file called `imi_output.tmp` when sbatch is called inside of the `run_imi.sh` sbatch. Then, …
=> Fix sbatch within sbatch printing

src/components/template_component/template.sh
This fixes a bug with the specification of the longitude bounds for the geoschem domain. According to the geoschem [documentation](https://geos-chem.readthedocs.io/en/latest/gcclassic-user-guide/geoschem-config.html#cmdoption-arg-latitude), the northernmost/southernmost grid boxes are half the size of others for both merra2 and geosfp. This only affects latitudes. Previously we were accounting for this for both lat and lon. This removes the correction for longitude.
=> bugfix/geoschem domain: fix bug in specification of geoschem domain for some custom domains

run_imi.sh, src/components/setup_component/setup.sh, src/utilities/download_TROPOMI.py
The goal of this feature is to reliably be able to identify what version of the IMI, geoschem version, and TROPOMI retrieval was used for a particular IMI run based solely on the config file. This will aid in reproducing inversion results.
The update copies the config file to the run directory and adds information like:
```
```
=> feature/imi-metadata collect geoschem version, IMI version, and tropomi retrieval version

src/inversion_scripts/operators/TROPOMI_operator.py, src/inversion_scripts/utils.py
Name: Megan He
This addresses the bug in #211 in which retrieval times can be rounded to a time outside of the period of interest due to rounding to the nearest hour. In the TROPOMI operator, an observation within the GC start and end dates can be rounded to be equal to the end date 00 hour, which is problematic because GC does not output for this hour. To avoid this problem, those dates are floor rounded.
=> Bugfix for TROPOMI operator retrieval times

src/components/jacobian_component/make_perturbation_sf.py, src/components/kalman_component/kalman.sh, src/components/kalman_component/prepare_sf.py, src/components/prior_component/prior.sh, src/components/template_component/template.sh, src/inversion_scripts/imi_preview.py, src/inversion_scripts/utils.py, src/notebooks/kf_notebook.ipynb, src/notebooks/visualization_notebook.ipynb
This addresses #237. 
When a non-kalman-filter inversion runs more than one month, HEMCO emissions files are generated for each month. In places like the preview and visualization notebook, only the first month of emissions are used. So if you ran a 1 year inversion, the emissions reported are just for January.
This update computes the daily emissions and updates them daily during the jacobian and posterior simulations.
I also add logic to compute the time averaged emissions for the inversion period for python scripts.
=> Bugfix/prior emissions: switch to daily precompiled emissions

src/components/statevector_component/statevector.sh, src/notebooks/statevector_from_shapefile.ipynb, src/utilities/make_state_vector_file.py, src/utilities/utils.py
Updates in https://github.com/geoschem/integrated_methane_inversion/pull/245 created a circular depenedency between the IMI preview and the prior simulation as documented in https://github.com/geoschem/integrated_methane_inversion/issues/253. This can be avoided by restoring the use of archived HEMCO standalone output in the generation of the state vector. Use of the HEMCO prior emissions have been removed from the state vector scripts.
New HEMCO standalone simulations have been performed archiving annual mean emissions for 2023 for 0.25x0.3125, 0.5x0.625, 2x2.5, and 4x5 degree global grids. These can be found in the GEOS-Chem data path HEMCO/CH4/v2024-07/HEMCO_SA_Output.
=> Restore use of archived HEMCO standalone output for generating state vectors

config.yml, envs/Harvard-Cannon/config.harvard-cannon.global_inv.yml, envs/Harvard-Cannon/config.harvard-cannon.yml
The MakePeriodCSV option was missing from the default config.yml file resulting in error messages in preview.sh. We now also set this option to false by default in all config files (including the Harvard-specific ones) since KalmanMode is also set to false by default.
=> Add Period CSV file options to default config.yml file and set MakePeriodsCSV to false by default

config.yml, envs/Harvard-Cannon/config.harvard-cannon.global_inv.yml, envs/Harvard-Cannon/config.harvard-cannon.yml, resources/containers/al2/container_config.yml, src/components/kalman_component/print_posterior_emissions.py, src/inversion_scripts/utils.py
* Arguments are passed as a string by default, so the filtering turned `period_df` into an empty DataFrame.
* `posterior_emis_ds` will never have a time dimension, so it can't be selected.
I tested this with this script. It feels like `MakePeriodsCSV` should default to `true` but maybe the IMI isn't set up to handle that based on #256 (unless #260 fixes that).
```
#!/bin/bash
git clone https://github.com/geoschem/integrated_methane_inversion.git
cd integrated_methane_inversion
git checkout 8b5bf2a # bugfix/kf-printing
sed -i -e "s|Test_IMI_Permian|Test_IMI_Permian_KF|g" \
-e "s|BlendedTROPOMI: false|BlendedTROPOMI: true|g" \
-e "s|KalmanMode: false|KalmanMode: true|g" \
-e "s|MakePeriodsCSV: false|MakePeriodsCSV: true|g" \
-e …
```
=> bugfix for printing posterior emissions

src/components/template_component/template.sh
In non-Kalman filter inversion longer than 32 days (@eastjames @sarahhancock etc.), DiagnFreq was being left as Monthly meaning it wouldn't be overwritten to daily here:
https://github.com/geoschem/integrated_methane_inversion/blob/235ff1443a482b72c4831aab47bfec0abc319820/src/components/prior_component/prior.sh#L75
This means the HEMCO standalone wasn't writing daily files and thus the averaging etc. is probably off by a factor of the number of days in each month.
=> default to End for DiagnFreq

config.yml, docs/source/getting-started/imi-config-file.rst, envs/Harvard-Cannon/config.harvard-cannon.global_inv.yml, envs/Harvard-Cannon/config.harvard-cannon.yml, resources/containers/al2/container_config.yml, src/components/inversion_component/inversion.sh
Optionally allow user to control the resources allocated to the inversion step separately from the `RequestedMemory` and `RequestedCPUs`. If `InversionMemory` and `InversionCPUs` are not set, then the default Memory and CPUs will be used.
=> add additional config variables to control inversion step resource allocation

src/notebooks/visualization_notebook.ipynb
Added cell to visualization notebook to save out stats from the notebook to the output directory (previously called plots)
Added stats are:
"PriorEmissions": total_prior_emissions,
"PosteriorEmissions": total_posterior_emissions,
"DOFS": DOFS,
"BiasPrior": prior_bias,
"BiasPosterior": posterior_bias,
"BiasPrior_std": prior_std,
"BiasPosterior_std": posterior_std,
"RMSEPrior": prior_RMSE,
"RMSEPosterior": posterior_RMSE,
"NumSuperObservations": count_obs_in_mask(mask, df_copy),
=> Stats Save from Notebook

src/inversion_scripts/get_jacobian_scalefactors.py
Name: Megan He
This fixes the calculation of scale factors to apply to the precomputed jacobian (previously in #275). The scale factor should be calculated as the reference perturbation scale factor divided by the "new" perturbation scale factor (i.e., `ref_pert_sf / pert_sf`. 
This ratio is effectively scaling the jacobian by the new total emissions divided by the reference total emissions: `ref_pert_sf / pert_sf = (target emissions / reference emissions) / (target emissions / new emissions) = new emissions / reference emissions`.
=> Bugfix for calculating jacobian scale factor

src/components/posterior_component/posterior.sh
Name: Megan He
Optimized OH scale factors in each hemisphere were not being applied in the posterior simulation. This PR modifies the posterior run's `HEMCO_Config.rc` to read in the hemispheric masks and apply the scale factors within `PerturbationsOH.txt` to the posterior simulation.
=> Fixes to apply optimized OH scale factors to posterior simulation

src/components/jacobian_component/jacobian.sh, src/inversion_scripts/get_jacobian_scalefactors.py, src/inversion_scripts/invert.py
Name: Megan He
Additional fixes when using the precomputed K option include only applying the K scaling factor to emissions elements when doing OH optimization, and defining/making directory paths.
=> Additional fixes for using precomputed Jacobian

src/inversion_scripts/operators/operator_utilities.py
Print out the jacobian number and date that is corrupt when calculating the jacobian matrix from the perturbation simulations. Shoutout to @megan-he for this. This can be very helpful for debugging errors.
=> Add informative error for corrupt Jacobian files

src/components/jacobian_component/make_perturbation_sf.py, src/inversion_scripts/invert.py, src/inversion_scripts/operators/TROPOMI_operator.py
When we calculate our jacobian matrix we do the following calculation:
`sensitivity_xch4 = delta_xch4 / perturbation`
where the perturbation is the fractional change from the original emissions eg. 50% perturbation translates to a perturbation = 0.5. 
However, in HEMCO_Config.rc, when we apply the perturbation, a 50% perturbation is represented by a scale factor of 1.5. 
Since the introduction of #226, we did not account for this difference between the representations of the perturbation in HEMCO vs in the jacobian calculation. This introduces an error in the jacobian calculation. Luckily, since the emission perturbations are relatively high (targeting 1e-08 kg/m2/s) the impact on results should be relatively small. For example, if an emission …
=> fix for misapplication of perturbation delta in jacobian sensitivity calculation

src/components/jacobian_component/jacobian.sh
Name: Stefanos Chatzimichelakis
Institution: Freelancer, on behalf of 2Celcius
Added missing output parameter in the prior simulation sbatch command when using pre-computed jacobian
The prior simulation sbatch command ran by the `PreComputedJacobian` branch of the `run_jacobian()` function of `src/components/jacobian_component/jacobian.sh` is expected to output to `imi_output.tmp` , but the `-o` parameter is missing, resulting in an unrecoverable error during the run.
=> minor fix to prior sbatch command

src/inversion_scripts/invert.py, src/inversion_scripts/lognormal_invert.py
In `lognormal_inverty.py` it was automatically assumed that the number of OH elements is 1 when setting `OptimizeOH: true`. This is only the case for regional simulations. For global simulations, OH_element_num should be 2.
In `invert.py`, a fix was needed to select the right element in K when using OH optimization in regional vs global simulations. In addition, the logicals for BC and OH optimization have been renamed in this script for consistency with `lognormal_invert.py`.
Also tagging @megan-he and @laestrada who brought this issue to my attention.
=> Add fixes to *invert.py scripts to properly determine number of OH elements

envs/aws/slurm/configure_slurm.py
Name: Stefanos Chatzimichelakis
Institution: Freelancer, on behalf of 2Celcius
Modified `configure_slurm.py` to use the `slurmd -C` output as-is, without hardcoded values or other manipulations, to fix a potential issue with wrong ThreadsPerCore and SocketsPerBoard values.
When the script parses the output of `slurmd -C` to add instance-specific directives to `/etc/slurmd/slurm.conf`, it takes the `CPUs` value and uses it for the `SocketsPerBoard` parameter, and also hardcodes `ThreadsPerCore` to 1. 
For example, for the recommended c5.x9large instance type, if `slurmd -C` outputs
`NodeName=ip-172-31-66-122 CPUs=36 Boards=1 SocketsPerBoard=1 CoresPerSocket=18 ThreadsPerCore=2 RealMemory=70305`
the resulting slurm.conf directive is
`NodeName=ip-172-31-66-122 CPUs=36 RealMemory=70305 …
=> Fix potential slurm misconfiguration

src/components/jacobian_component/jacobian.sh
Name: James East
In the lognormal inversion, the background simulation has TROPOMI initial and boundary conditions, OH loss, and no emissions. It should also have soil absorption, but it doesn't. This PR turns on MeMo soil absorption in the background simulation in lognormal inversions. Lognormal inversions done without this fix have an overcorrection, the magnitude is probably small.
Without soil absorption turned on in the background, Kx+background does not match the prior/posterior simulation:
With soil absorption in the background simulation, Kx+background matches the prior/posterior simulation:
=> Turn soil absorption on in background simulation

src/inversion_scripts/merge_partial_k.py
Name: James East
Speed up `merge_partial_k.py` by pre-allocating a list that will contain the jacobian before looping through the files. Previously, we concatenated an array as we went, but this was slow. For a particularly large case for me, `merge_partial_k.py` was taking >60 mins. With this change, it took <3 mins.
Not yet tested with dev.
=> Speed up merge_partial_k.py by pre allocating list

src/components/jacobian_component/make_perturbation_sf.py
This bugfix properly generates the `effective_pert_sf`for calculation of the Jacobian. This change only affects the Kalman Filter IMI mode because the `effective_pert_sf` also needs to account for scaling the Jacobian according to the nudged prior emissions from the previous period.
Thanks, Matt Thill, for finding this and @eastjames for helping to think it through.
=> bugfix for KF perturbation factor calculation

src/components/statevector_component/statevector.sh, src/notebooks/statevector_from_shapefile.ipynb, src/utilities/utils.py
The HEMCO standalone output were updated to include the latest emission updates now in GEOS-Chem 14.6.2. This includes
- Updating the bottom-up global CH4 oil, gas, and coal emissions to GFEI v3
- Updating rice emissions to the Global Rice Paddy Inventory (GRPI)
- Fixes for seasonality of hydropower reservoir and livestock emissions
=> Update HEMCO standalone output to files generated with HEMCO 3.11.1 and GEOS-Chem 14.6.2 emissions

config.yml, docs/source/getting-started/imi-config-file.rst, envs/Harvard-Cannon/config.harvard-cannon.12km.yml, envs/Harvard-Cannon/config.harvard-cannon.global_inv.yml, envs/Harvard-Cannon/config.harvard-cannon.yml, envs/MSU-HPC_Orion/config.msu-hpc_orion.global_inv.yml, resources/containers/al2/container_config.yml, src/utilities/download_bc.py, src/write_BCs/README.md, src/write_BCs/config_boundary_conditions.yml, src/write_BCs/run_boundary_conditions.sh, src/write_BCs/write_boundary_conditions.py
Currently, we remove our smoothed column bias equally from all 47 vertical layers of the originally simulated mixing ratio profiles:
```
new_gc_mixing_ratio = original_gc_mixing_ratio - bias
```
Instead, I now scale the originally simulated mixing ratio profiles:
```
new_gc_xch4 = original_gc_xch4 - bias
new_gc_mixing_ratio = original_gc_mixing_ratio * (new_gc_xch4 / original_gc_xch4)
```
The impact isn't large, but I believe this is a more realistic strategy at high bias values. See below for global average profiles for 2019–2024 with the old and new method, the difference between these profiles, and finally the spatial differences that result from going from GEOS-Chem 14.4.1 to 14.6.2 (mostly the reversion from EDGAR v8 to v7 livestock …
=> Update to v2025-06 BCs

src/components/template_component/template.sh
The default date string in template_run/geoschem_config.yml for CH4 runs was 20190101. This is not the case for 12km runs though because fields at that resolution are not available until mid-2021. When users set up a 12km GEOS-Chem run directory, the date in geoschem_config.yml is set to 20230101 by default.
The code in template.sh has been updated to look for the correct date string based on grid resolution and replace it with the start and end dates as defined in the IMI config file.
=> Fix date string in geoschem_config.yml for 12km runs

src/components/preview_component/preview.sh, src/inversion_scripts/imi_preview.py, src/inversion_scripts/jacobian.py
Name: Dandan Zhang
- In imi_preview.py, the inversion area cannot be calculated correctly with [the function](https://github.com/geoschem/integrated_methane_inversion/blob/main/src/inversion_scripts/imi_preview.py#L171) used there. Instead, an alternate method of estimating number of grid box is used as implemented in [src/inversion_scripts/imi_preview.py](https://github.com/geoschem/integrated_methane_inversion/pull/337/files#diff-f40c1bfd264189b9d4ee3f03c2a48806fb96f2e2029f02520e32a755c8ebf9ec). This will fix the error stated in https://github.com/geoschem/integrated_methane_inversion/issues/331 for the cost estimation in imi_preview.py.
- Fix the error for calculating averaging kernel density as well as stated in …
=> Fix error in imi_preview for estimating computing cost and averaging kernel sensitivity
