- src/inversion_scripts/imi_preview.py
- src/inversion_scripts/jacobian.py
This PR skips processing of a TROPOMI file if the file is corrupt.
> Bugfix/corrupt tropomi_files: Handle corrupt tropomi files

- envs/Harvard-Cannon/config.harvard-cannon.yml
- src/components/preview_component/preview.sh
- src/inversion_scripts/imi_preview.py
- src/utilities/sanitize_input_yaml.py
@nicholasbalasus -- going off of your PR:
Conditionally change the memory allocated by sbatch for the imi_preview based on whether running on aws or local cluster.
> conditionally change memory for preview

- src/components/template_component/template.sh
> MERRA2 compatibility in GEOS-Chem template dir

- docs/source/advanced/using-clustering-options.rst
- src/components/statevector_component/aggregation.py
Incorporate point sources into clustering algorithm by forcing high resolution for elements as specified by given lat/lon. This update allows the use of a csv file to pass in the lat/lons.
Additionally, I added documentation on how to use this feature.
> Point source incorporation into clustering algorithm via csv file

- config.yml
- docs/source/getting-started/imi-config-file.rst
- envs/Harvard-Cannon/config.harvard-cannon.yml
- src/components/inversion_component/inversion.sh
- src/components/posterior_component/posterior.sh
- src/components/preview_component/preview.sh
- src/components/spinup_component/spinup.sh
- src/components/statevector_component/statevector.sh
- src/geoschem_run_scripts/submit_jacobian_simulations_array.sh
- src/utilities/sanitize_input_yaml.py
- update the IMI to take an additional config variable `SchedulerPartition`. This eases use on local clusters by using the `-p` flag when using `sbatch` commands.
tested on aws.
> feature allow specification of partition for sbatch commands

- src/components/jacobian_component/jacobian.sh
- src/components/setup_component/setup.sh
- src/write_BCs/run_boundary_conditions.sh
Update to GC 14.2.1. Note that the default test case has less DOFs now, but I think that is because the prior is very different now. 
[visualization_notebook 3.html.zip](https://github.com/geoschem/integrated_methane_inversion/files/12885966/visualization_notebook.3.html.zip)
> update to GC 14.2.1

- run_imi.sh
- src/components/inversion_component/inversion.sh
- src/components/setup_component/setup.sh
Depending on the conda/miniconda/mamba distribution the way we load conda is faulty. It's best to source the bashrc file directly imo. This also makes it compatible with micromamba aliased as conda.
> conda activate bugfix

- run_imi.sh
- src/components/inversion_component/inversion.sh
- src/components/preview_component/preview.sh
- src/components/statevector_component/statevector.sh
- src/inversion_scripts/run_inversion.sh
- src/utilities/download_TROPOMI.py
- src/utilities/download_blended_TROPOMI.py
The blended TROPOMI+GOSAT dataset is now available for download from AWS. This PR facilitates automatic download for use on AWS.
Additionally I replace the default observational directory to be named `satellite_data` instead of `data_TROPOMI`
> Feature/blended TROPOMI+GOSAT download script

- src/utilities/download_TROPOMI.py
- src/utilities/download_blended_TROPOMI.py
Modifies `download_TROPOMI.py` to use `boto3` to be consistent with the changes made in #205. This also allows the script to download the latest TROPOMI data (version 02.06.00) that the previous script was not set up for.
Relative to what we have on Cannon (which I source directly from Copernicus), this script reveals that the following files are missing from the MEEO S3 bucket. I sent MEEO an email about this.
```
S5P_OFFL_L2__CH4____20230825T045154_20230825T063323_30387_03_020500_20230826T204654.nc
S5P_OFFL_L2__CH4____20230825T150050_20230825T164219_30393_03_020500_20230827T064405.nc
S5P_OFFL_L2__CH4____20230825T232817_20230826T010946_30398_03_020500_20230827T152703.nc
S5P_OFFL_L2__CH4____20231217T223919_20231218T002049_32015_03_020600_20231219T144 …
```
> Update operational TROPOMI data download script

- run_imi.sh
- src/utilities/download_TROPOMI.py
Give resources to the operational download script as was done in #205 and I forgot to do in #209.
> Give operational download script more resources

- src/inversion_scripts/imi_preview.py
Update the IMI preview to visualize the state vector in a plot
> plot state vector as part of imi preview

- src/inversion_scripts/plumes.py
Name: James East
Fix a bug that led to a fatal error if no plumes were detected in the inversion region/period. Solves #228. I tested and the out of the box preview runs successfully.
> Fix logic for case when no plumes available

- src/inversion_scripts/invert.py
- src/inversion_scripts/lognormal_invert.py
- src/inversion_scripts/merge_partial_k.py
Applies a fix for a bug where we scale superobservation error standard deviations instead of error variances, as described in #234.
> bugfix for scaling of So

- src/inversion_scripts/postproc_diags.py
Postproc_diags.py addresses geoschem not generating the 0th hour of the initial SpeciesConc file for the simulation start date by merging the 0th hour data from either the spinup run or the previous posterior simulation (kalman mode).
This fixes two bugs in postproc_diags.py:
1) Since the addition of multitracer jacobian runs, postproc_diags would only be applied to a single tracer in each jacobian run, rather than all tracers. This caused all other tracers to be assigned NaN values for the 0th hour. Here, we add additional variables to the spinup/posterior SpeciesConc file for each tracer
2) In some cases on a rerun of postproc_diags.py in kalman mode, the following error can happen:
```
xarray.core.merge.MergeError: conflicting values for …
```
> fix postproc_diags to include 0 hour for all tracers and only merge 0th hour

- src/inversion_scripts/imi_preview.py
- src/inversion_scripts/plumes.py
- src/utilities/parse_yaml.py
This fix addresses issue #240  by expanding OutputPath explicitly.
> Expand variables in parse_yaml.py script.

- docs/source/getting-started/imi-config-file.rst
- envs/Harvard-Cannon/config.harvard-cannon.global_inv.yml
- envs/Harvard-Cannon/config.harvard-cannon.yml
- src/components/kalman_component/kalman.sh
- src/components/preview_component/preview.sh
- src/inversion_scripts/imi_preview.py
Name: Megan He
This includes a <10% ice cover threshold for generating the global state vector that excludes Greenland, and an option to use a custom periods.csv to define Kalman Filter update periods (e.g. there are an uneven number of days in each month). There are also minor plotting fixes.
> Additional changes for global inversion

- src/notebooks/kf_notebook.ipynb
Name: Megan He
Minor addition.
> Add lat/lon bounds for 2x2.5

- src/components/template_component/template.sh
- src/utilities/common.sh
Accounts for GC bounds being grid cell edges. Initially addressed in #190 but fixed fully here.
> account for GC bounds being grid box edges

- src/components/jacobian_component/jacobian.sh
- src/components/template_component/template.sh
This update adds the following scale factor to the template HEMCO_Config.rc:
```
5 ZERO            0.0 - - - xy 1 1
```
rather than on the fly during jacobian.sh. 
This is to prevent issues where users add custom scale factors in their template directory and use the same id or name.
> Move zero scale factor addition to template.sh

- src/write_BCs/README.md
- src/write_BCs/config_boundary_conditions.yml
- src/write_BCs/write_boundary_conditions.py
Updating outdated README + comments.
> fix boundary condition readme

- src/notebooks/visualization_notebook.ipynb
Added start/end date to stats csv output from viz notebook. Super simple two line addition to viz notebook.
> added start/end date to stats csv output from viz notebook

- docs/source/getting-started/IMI-glossary.rst
- docs/source/getting-started/best-practices.rst
- docs/source/getting-started/faqs.rst
- docs/source/index.rst
Update the readthedocs documentation with best practices, faqs, and an imi glossary
> update the readthedocs with faqs, glossary, and best practices

- envs/Harvard-Cannon/config.harvard-cannon.global_inv.yml
- envs/Harvard-Cannon/config.harvard-cannon.yml
- src/write_BCs/config_boundary_conditions.yml
Name: lucas Estrada
Update cannon paths to reflect new partitions
> update config paths to reflect new paths on cannon

- src/inversion_scripts/plumes.py
Name: James East
Bug fixes for getting open source plume data and speeding up plume data download from carbon mapper
> Fixes #231. Updates to carbonmapper API and fixes to IMEO

- src/inversion_scripts/operators/operator_utilities.py
Name: Peter Ivatt
Institution: University of Rochester
In the process of investigating issue #314 and testing the changes proposed in #280 , I implemented a few small changes to `operator_utilities.py` that significantly reduced memory usage.
It appears that as the number of elements increases, memory usage eventually explodes. When running with 1587 elements over the NA grid, the peak memory demand reached 14.3GB, while the underlying data size was only 1.8GB. This can be addressed by moving the hour selection step prior to the first concatenation, which substantially reduces the amount of data that needs to be concatenated. This change reduced memory demands for this run to 3.24GB.
The second improvement involved looping over all datasets before the second concatenation and loading them …
> Optimized Dask-driven Xarray functions for performance.

- src/inversion_scripts/invert.py
- src/inversion_scripts/lognormal_invert.py
Name: Megan He
When weighting the prior OH error terms in the prior error covariance matrix `Sa` in `invert.py` following Maasakkers et al. (2019), this "constraint matrix" should only be used to calculate the solution xhat (`delta_optimized`). The unweighted errors in the original `Sa` should be used to calculate the posterior error covariance matrix `S_post` and the averaging kernel sensitivity matrix `A`. 
Also addresses OH error weighting in the lognormal inversion code.
> Use constraint matrix to calculate solution in OH optimization

- src/utilities/make_state_vector_file.py
deg_lat and deg_lon need to be set correctly in make_state_vector.py
> add 12km resolution
